import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Aside from "@/components/Aside";
import WeatherProvider from "@/components/WeatherProvider.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex bg-background text-foreground h-[100svh] items-stretch`}
      >
        <WeatherProvider>
          <Aside />

          {children}
        </WeatherProvider>
      </body>
    </html>
  );
}
